### PR TITLE
set other encoding for dbf

### PR DESCRIPTION
**Pull request by ArtiiP**

### CODE REVIEW

**Comment by ArtiiP** [comment]
pull for issue #46 
it's tested on py3 only

**Comment by micahcochran** [comment]
Thanks @ArtiiP .  This seems like an improvement, currently it only give a byte string that isn't decoded.

I tried this out in Python 2 & 3 using [japan_poly](https://hub.qgis.org/issues/5911), which is using code page cp932 (similar to Shift-JIS?).

```Python
In [1]: import shapefile

In [2]: s=shapefile.Reader('japan_poly', encoding='cp932')

In [3]: s.records()
# Python 3.4 results  (correctly decoded)
[['北海道 (Hokkaido)'], ['本州 (Honshu)'], ['四国 (Shikoku)'], ['九州 (Kyushu)']]
# Python 2.7 results  (before this patch Python 3.4 would give this same byte string type result)
[['\x96k\x8aC\x93\xb9 (Hokkaido)'],
 ['\x96{\x8fB (Honshu)'],
 ['\x8el\x8d\x91 (Shikoku)'],
 ['\x8b\xe3\x8fB (Kyushu)']]
```

Shouldn't Python 2's results be unicode strings?  Will that break something?

Here's the Python 2.7 IPython console:
```Python
In [8]: s.records()[0][0]
Out[8]: '\x96k\x8aC\x93\xb9 (Hokkaido)'

In [4]: s.records()[0][0].decode('cp932')
Out[4]: u'\u5317\u6d77\u9053 (Hokkaido)'

In [5]: print(s.records()[0][0].decode('cp932'))
北海道 (Hokkaido)

In [6]: print(s.records()[0][0])
�k�C�� (Hokkaido)
```

I am using this commit to create code that will automatically determine the encoding based on .CPG or .DBF's language ID (see issue #46).  My initial results are promising.

@ArtiiP do you want to attempt to fix this for Python 2.x or should I try fixing it?

**Comment by ArtiiP** [comment]
> Shouldn't Python 2's results be unicode strings? Will that break something?

that's really problematic part of py2

> @ArtiiP do you want to attempt to fix this for Python 2.x or should I try fixing it?

I don't have py2 to testing, go ahead :)

**Comment by wsw0108** [comment]
For py2, we can use codecs.decode(). @micahcochran @ArtiiP 

```python
def u(v, encoding=):
    if PYTHON3:
        ...
    else:
        # For python 2 assume str passed in and return str.
        import codecs
        try:
            return codecs.decode(v, encoding)
        except: return v
```

**Comment by karimbahgat** [comment]
House-cleaning: All encoding-related issues and PRs have been collected in and can be referenced from #74.

**Pull request closed without merging**
