### PR TITLE
Test improvements

### PR DESCRIPTION
**Pull request by ARF1**
Incorporates rebased  #43.
Closes #43.
- Merge pull request #43 from micahcochran/add-travis
- restore & fix iterShapeRecords() doctest
- remove test verbosity to make it easier to spot the test failures
- clean up temp files after running tests
- add .gitignore & remove databases created by the tests

[Travis CI build log](https://travis-ci.org/ARF1/pyshp/builds/122458549).

### CODE REVIEW

**Comment by micahcochran** [comment]
Very good.  

"All test passed successfully."  I like it.

**Comment by karimbahgat** [comment]
Does anyone know if this has already been incorporated in another PR? If this gets updated to resolve the conflicts I will do my best to merge it right away.

**Comment by ARF1** [comment]
@karimbahgat Feel free to take ownership of this issue. I keep not being able to find the time to update it.

**Comment by karimbahgat** [comment]
Great. Seems like most of these have been addressed in some way by previous contributions. Others were incorporated in #95. 

Didn't address the test file cleanup, as I am not sure what problems or test errors might come of it. If anyone else is willing to go down this route that's fine too, but for now I'm okay leaving this as is. 

Therefore considering this mostly fixed.

**Pull request closed without merging**
