### PR TITLE
Fixes for records() speedup

### PR DESCRIPTION
**Pull request by karimbahgat**
This fixes the issues and doctest-failures introduced in the records() speedup #62, see issue #66. 

Problem was I thought all row values were unpacked with the correct format, but instead they are unpacked as strings and have to be manually parsed into their appropriate types. Also forgot to account for the DeleteFlag field when grouping the flat rowlist into rows. 

In order to fix these issues, this PR moves the row value type parsing into a separate method and calling it where necessary.

### CODE REVIEW

**Comment by karimbahgat** [comment]
Actually, it appears the 20x speedup was almost entirely from not having to parse the value types. After this fix, the batch "records()" method seems to not have any noticable speedup from the original. So not sure the changes to the internal API are worth it. 

Closing this. I suggest just changing "records()" back to the pre-speedup merge.

**Comment by karimbahgat** [comment]
I.e, this should fix it back to normal: 

```
    def records(self):
        """Returns all records in a dbf file."""
        if not self.numRecords:
            self.__dbfHeader()
        records = []
        f = self.__getFileObj(self.dbf)
        f.seek(self.__dbfHeaderLength())
        for i in range(self.numRecords):
            r = self.__record()
            if r:
                records.append(r)
        return records
```

**Comment by micahcochran** [comment]
@GeospatialPython 
How do you want to handle this?  Does someone need to put a PR together to restore the records() function?

**Comment by karimbahgat** [comment]
I put together PR #68 that reverts records() to the original, which should do it. All tests pass.

**Pull request closed without merging**
