### PR TITLE
Allow generation of empty (zero record) shapefile

### PR DESCRIPTION
**Pull request by StephenClouse**
We are using pyshp inside NOAA for a project involving NWS weather warnings, and we had a requirement that if there are no active warnings, we should generate an empty shapefile. Currently pyshp errors on this case while trying to determine extents. This adds a sanity check and sets the extents to all zeroes if there are no shapes in the file.

### CODE REVIEW

**Comment by micahcochran** [comment]
Could this be accomplished with a Null Shape?  I know it is a rather obscure feature of the shape file format.

I think it is great that NOAA is using pyshp.

**Comment by StephenClouse** [comment]
They specifically asked for a shapefile with a zero feature/record count. ¯\_(ツ)_/¯

**Comment by Nodd** [comment]
I'm interested in this feature too.

**Comment by karimbahgat** [comment]
This seems to have been fixed already in a previous commit, bbox is only calculated if lenght of points > 0. So the following works:

```
import shapefile
w = shapefile.Writer(shapefile.NULL)
w.save("empty.shp")
```

**Pull request closed without merging**
