### PR TITLE
Enhanced __geo_interface__

### PR DESCRIPTION
**Pull request by jzmiller1**
Creating a pull request that has the work I've linked to you previously about **geo_interface** so we can discuss it here.  This is not really ready to merge and it is just for discussion at this point.  I would like to hear what you think about it.  If you did want to merge it in I would want to do some clean up on my code first that I haven't had time to get to yet.

### CODE REVIEW

**Comment by GeospatialPython** [comment]
I haven't forgotten about this and have started reviewing it.  No objections so far.

**Comment by jzmiller1** [comment]
I am taking another look at this in the next month.  I know there are a few
changes that I need to make.  Just let me know if you have any feedback.

**Comment by GeospatialPython** [comment]
Will do.  I am committed to going down this path.

**Comment by jzmiller1** [comment]
I'm still hoping to get back to this soon.  I am working on getting support for Features and Feature collections into tehe pygeoif repository (cleder/pygeoif#7).  I'd like to get that worked out before coming back to clean up this pull request.  If you have any new thoughts or feedback just let me know.

**Comment by cleder** [comment]
the changes were merged in pygeoif, is there any other blocker for the merge?

**Comment by jzmiller1** [comment]
This is a fairly large change in how the geo_interface portion of pyshp works.  I'm comfortable with updating this after some of the other open PRs get merged in if that makes it easier to get this merged.

**Comment by jzmiller1** [comment]
Anyone interested in looking at this and merging it in at some point?  It isn't 100% complete...I was looking to get some feedback before I finished it off.  If there's no interest in it I don't want to spend time on it as it will take me a bit to remember what I was doing here.

**Comment by karimbahgat** [comment]
I personally like this idea of expanding the geo interface to also cover features and collections and it seems to have been implemented well. However, unless there are some other benefits I am missing, I am a bit skeptical of implementing it as a mixin class. Primarily since this is a somewhat big fundamental change to how the lib works, and the subclassing and nested inheritance adds a new level of complexity and potential things that can go wrong. The extent of these changes is what has kept me from looking at it until now. 

Others might have another opinions, but if you were to implement them as separate methods directly to the objects that need them, i.e. geo interface for _Shape, ShapeRecord, and Reader (any more?), I would be much more supportive of merging it.

**Comment by jzmiller1** [comment]
There's definitely some more work that needs to be done on this before it is ready,  I still need to update the docs/tests and handle a couple of things like MultiPolygons properly.  

The GeoInterfaceMixin only touches _Shape, _ShapeRecord and _ShapeRecords and doesn't impact the reader or the writer at all.  The class only implements the geointerface methods and nothing else.  If we don't use the Mixin method we would end up duplicating the code in three places and it would be more difficult to maintain.  

Would any new tests or additions to the docs that explain the mixin behavior help make using the mixin method more palatable?

**Comment by karimbahgat** [comment]
I was able to have a more detailed read of your code. I think your push to add feature and featurecollection geo interfaces is really great and much needed, but on second thought duplication isnt really an issue here. Consider the following approach: 

1. Keep the main geojson implemention with the _Shape object, as it currently stands. 
2. For _ShapeRecord, the geo interface method creates a dictionary of type "Feature" and for the "geometry" entry simply populate it by calling on the `.shape.__geo_interface__`, so no duplication needed. For the "properties" entry populate it using `.fields` and `.record`, which you rightly added. 
3. I don't think we should add a separate _ShapeRecords (plural) object, more natural to stick with the native list type. Besides, I think it would be much more natural to have the feature collection as the geo interface on the Reader object. No duplication needed here either, simply creating the list of features by calling geo interface for each _ShapeRecord. The featurecollection bbox can be read directly from the reader. 

With the mixin class, you are essentially outsourcing the geo interface behavior with a bunch of conditions on the type, instead of just keeping the code logically grouped to each class. 

If this makes sense, create a new PR in line with this modified approach, and I will be happy to merge it.

**Comment by jzmiller1** [comment]
If ShapeRecords is to remain a Python list then it can't have a `__geo_interface__`.  The list built in doesn't have all of the attributes of a normal object:

```
>>> [].__dict__
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'list' object has no attribute '__dict__'
```
Are you willing to accept something that uses the new ShapeRecords object?

**Comment by karimbahgat** [comment]
That's right, keeping .shapeRecords() results as a list means that it cannot have a geo interface. Which is how I would prefer it, since the main purpose of it is to loop through, and .shapes() and .records() also return just a list. So rather than adding a new ShapeRecords (plural) class, I would accept if you instead added a featurecollection geo interface to the entire Reader class. Does that make sense/would you be willing to go down that route? Again, it's great that you're taking this initiative.

**Comment by jzmiller1** [comment]
I'd like to be able to call `__geo_interface__` on shapeRecords and shapes as they map to GeometryCollection and FeatureCollection.

I just force pushed some changes to my fork so the commits don't line up properly with this thread.  The old mixin code is gone.  There is still a good bit of work to be done to ensure that this is actually generating the right GeoJSON but it is working as an example for now.

This is what we have on the master branch now:

```
>>> import shapefile
>>> r = shapefile.Reader('shapefiles/test/line')
>>> r.__geo_interface__
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'Reader' object has no attribute '__geo_interface__'
>>> s = r.shapes()
>>> s[0].__geo_interface__
{'type': 'LineString', 'coordinates': ((1.0, 5.0), (5.0, 5.0), (5.0, 1.0), (3.0, 3.0), (1.0, 1.0))}
>>> s.__geo_interface__
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'list' object has no attribute '__geo_interface__'
>>> shapeRecs = r.shapeRecords()
>>> shapeRecs.__geo_interface__
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'list' object has no attribute '__geo_interface__'
```

This is what we would have if we can make some changes via a Mixin or some kind of subclass for a list:

```
>>> import shapefile
>>> r = shapefile.Reader('shapefiles/test/line')
>>> r.__geo_interface__
{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((1.0, 5.0), (5.0, 5.0), (5.0, 1.0), (3.0, 3.0), (1.0, 1.0)), 'bbox': (1.0, 1.0, 5.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'First', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((1.0, 3.0), (5.0, 3.0)), 'bbox': (1.0, 3.0, 5.0, 3.0)}, 'properties': {'properties': {'FIRST_FLD': 'Second', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}], 'bbox': (1.0, 1.0, 15.0, 5.0)}
>>> s = r.shapes()
>>> s[0].__geo_interface__
{'type': 'LineString', 'coordinates': ((1.0, 5.0), (5.0, 5.0), (5.0, 1.0), (3.0, 3.0), (1.0, 1.0)), 'bbox': (1.0, 1.0, 5.0, 5.0)}
>>> s.__geo_interface__
{'type': 'GeometryCollection', 'geometries': [{'type': 'LineString', 'coordinates': ((1.0, 5.0), (5.0, 5.0), (5.0, 1.0), (3.0, 3.0), (1.0, 1.0)), 'bbox': (1.0, 1.0, 5.0, 5.0)}, {'type': 'LineString', 'coordinates': ((1.0, 3.0), (5.0, 3.0)), 'bbox': (1.0, 3.0, 5.0, 3.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}], 'bbox': (1.0, 1.0, 15.0, 5.0)}
>>> shapeRecs = r.shapeRecords()
>>> shapeRecs.__geo_interface__
{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((1.0, 5.0), (5.0, 5.0), (5.0, 1.0), (3.0, 3.0), (1.0, 1.0)), 'bbox': (1.0, 1.0, 5.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'First', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((1.0, 3.0), (5.0, 3.0)), 'bbox': (1.0, 3.0, 5.0, 3.0)}, 'properties': {'properties': {'FIRST_FLD': 'Second', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}, {'type': 'Feature', 'geometry': {'type': 'LineString', 'coordinates': ((10.0, 5.0), (15.0, 5.0), (15.0, 1.0), (13.0, 3.0), (11.0, 1.0)), 'bbox': (10.0, 1.0, 15.0, 5.0)}, 'properties': {'properties': {'FIRST_FLD': 'Appended', 'SECOND_FLD': 'Line'}}}], 'bbox': (1.0, 1.0, 15.0, 5.0)}
```

**Comment by sventech** [comment]
With GeoJSON becoming more dominant in geospatial circles, it would be really great to have this functionality included, since it would allow easier conversion between formats.

**Comment by karimbahgat** [comment]
Just added this functionality, so in the next version there should be full support for geo interface on all relevant objects: Shape, Shapes, ShapeRecord, ShapeRecords, plus Reader. Implemented as simple list subclasses with the additional __geo_interface__ method.

**Comment by karimbahgat** [comment]
Now available in version 2.1.0

**Pull request closed without merging**
